### ISSUE TITLE
.Net profile version

### ISSUE THREAD

**Issue by leye0** [NVentimiglia/Websockets.PCL#3]
Useful and awesome library!

Could you add a .NET 4.5 version (same as 4.5.2, but targetting 4.5.0)? I've had to add the original .NET source to one of my Xamarin project (Gtk# 2.0) in order to compile it as 4.5.0.

I'm totally for including a 4.5.2 version, but in the cross-platform world, not all environments and solution setups are using .NET Core yet. :) In this case, I have a Xamarin.Forms app and a desktop app in GTK communicating with the mobile apps.

Thanks!
Leon

**Comment by NVentimiglia** [comment]
I will look into this., I will also accept pull requests.

**Comment by NVentimiglia** [comment]
Took a look, the package includes a .net 4.5 dll. This is forward compatible.

**Comment by leye0** [comment]
Oh, good, I'll retry then. Thanks.
