### ISSUE TITLE
Specifying at which port WebSocket is listening

### ISSUE THREAD

**Issue by leye0** [NVentimiglia/Websockets.PCL#4]
Is there a way to specify where my WebSocket listener will listen to connection and message? I've tried to use WebSocket between devices with no success. I was able with WebSocket4Net.

**Comment by NVentimiglia** [comment]
This is a client library only, not a server. If you need a server I can recommend Fleck or NetGains.

**Comment by leye0** [comment]
Ah, actually I was missing the point about WebSocket basics. I needed a
WebSocket server too. Thanks.
